Hafta1Odev.Web/Models/ErrorViewModel.cs
namespace Hafta1Odev.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hafta1Odev.Web/Models/UrunListele/UrunListeleViewModel.cs
namespace Hafta1Odev.Web.Models.UrunListele
{
    public class UrunListeleViewModel
    {
        public int Id { get; set; }
        public string Renk { get; set; }
        public string UrunAdi { get; set; }
        public decimal Fiyat { get; set; }
    }
}

Hafta1Odev.Web/Controllers/HomeController.cs
using Hafta1Odev.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hafta1Odev.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hafta1Odev.Web/Controllers/UrunEklemeController.cs
using Hafta1Odev.Data;
using Microsoft.AspNetCore.Mvc;

namespace Hafta1Odev.Web.Controllers
{
    public class UrunEklemeController : Controller
    {
        Veritabani veritabani = new Veritabani();
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UrunEkle(UrunModel urun)
        {
            veritabani.UrunEkle(urun);
            return View("/Views/UrunEkleme/Index.cshtml");
        }
    }
}

Hafta1Odev.Web/Controllers/UrunListeleController.cs
using Hafta1Odev.Data;
using Microsoft.AspNetCore.Mvc;

namespace Hafta1Odev.Web.Controllers
{
    public class UrunListeleController : Controller
    {
        Veritabani veritabani = new Veritabani();
        public IActionResult Index()
        {
           List<UrunModel> model = veritabani.TumUrunler();
            
            return View(model);
        }
    }
}

Hafta1Odev.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Hafta1Odev.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hafta1Odev.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hafta1Odev.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hafta1Odev.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Hafta1Odev.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Hafta1Odev.Web/Views/UrunEkleme/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Hafta1Odev.Data.UrunModel


<div>
    @using (Html.BeginForm("UrunEkle", "UrunEkleme", FormMethod.Post))
    {
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th colspan="2" align="center">Person Details</th>
            </tr>
@*            <tr>
                <td>PersonId: </td>
                <td>
                    @Html.TextBoxFor(m => m.Id)
                </td>
            </tr>*@
            <tr>
                <td>Urün Adı: </td>
                <td>
                    @Html.TextBoxFor(m => m.UrunAdi)
                </td>
            </tr>
            <tr>
                <td>Renk: </td>
                <td>
                    @Html.TextBoxFor(m => m.Renk)
                </td>
            </tr>
            <tr>
                <td>Fiyat: </td>
                <td>
                    @Html.TextBoxFor(m => m.Fiyat)
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit"/></td>
            </tr>
        </table>
    }

 </div>

Hafta1Odev.Web/Views/UrunListele/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Hafta1Odev.Data.UrunModel>

<div class="text-center">
    <h1 class="display-6">Ürün Listele Ekranı</h1> <br /><br />
    
    <table style="width:100%">
      <tr>
        <th>Id</th>
        <th>Ürün Adı</th>
        <th>Renk</th>
        <th>Fiyat</th>
      </tr>
     
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.UrunAdi</td>
                <td>@item.Renk</td>
                <td>@item.Fiyat</td>
            </tr>
        }

    </table>

</div>


<style>
    table, th, td {
  border:1px solid black;
}
</style>